# Generated by Django 4.2.7 on 2023-12-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
