# Generated by Django 4.2.7 on 2023-12-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_orderitem_unique_order_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
