# Generated by Django 4.2.7 on 2023-12-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
